- type: replace
  path: /releases?/name=load-balancer?
  value:
    name: load-balancer
    version: 0.2.2
    url:     https://github.com/genesis-community/load-balancer-boshrelease/releases/download/v0.2.2/load-balancer-0.2.2.tgz
    sha1:    38aace530188c44eef3522762028a5d5d166dda1