---
meta:
  default:
    azs: [z1]

instance_groups:
  - name:      load-balancer
    instances: 1
    azs:       (( grab params.availability_zones || meta.default.azs ))
    stemcell:  default
    networks:
    - name:       (( grab params.haproxy_network || "default" ))
      static_ips: (( static_ips (4, 3, 255)))
    vm_type:   (( grab params.vm_type || "default" ))

    jobs:
    - name: haproxy
      release: load-balancer
      properties:
        advanced: (( grab params.advanced_haproxy_config  ))
        load-balancers: (( grab params.load_balancers  ))

update:
  serial:            false
  canaries:          1
  max_in_flight:     1
  max_errors:        1
  canary_watch_time: 5000-600000
  update_watch_time: 5000-600000

stemcells:
  - alias:   default
    os:      (( grab params.stemcell_os      || "ubuntu-xenial" ))
    version: (( grab params.stemcell_version || "latest" ))

releases:
- name:    load-balancer
  version: 0.1.0
  url:     https://github.com/genesis-community/load-balancer-boshrelease/releases/download/v0.1.0/load-balancer-0.1.0.tgz
  sha1:    9631ddbac1ef3431612a2d11220ab0bc6f0ae813
