#!/bin/bash
shopt -s nullglob
set -eu

#
# Genesis Kit `new' Hook
#
cat <<EOF >$GENESIS_ROOT/$GENESIS_ENVIRONMENT.yml
kit:
  name:    $GENESIS_KIT_NAME
  version: $GENESIS_KIT_VERSION

params:
  load_balancers:
  - name: front-door # ---------- an EXAMPLE load balancer
    mode: http       #            you can have lots of these...
    port: 443
    acls:
    - name: allow-internal
      allow:
        - 10.0.0.0/8
    backend:
      addresses:
        - 10.2.1.1

    tls:
      certificates: ~
  advanced_haproxy_config: null
  haproxy_network: default
  vm_type: default
EOF
exit 0
